name: analyst  
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - python-dotenv
    - llama-index==0.10.58
    - llama-cloud==0.0.6
    - llama-index-core==0.10.58 
    - llama-index-readers-file==0.1.27
    - llama-index-agent-openai==0.2.9
    - llama-index-embeddings-openai==0.1.10
    - llama-index-llms-openai==0.1.27
    - numpy==1.26.4
    - pandas==2.2.2
    - openai==1.35.10
    - openpyxl