name: analyst  
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 
  - pip
  - pip:
    - python-dotenv
    - llama-index
    - llama-index-readers-file
    - llama-index-agent-openai
    - llama-index-embeddings-openai
    - llama-index-llms-openai